In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import plotly.express as px
import plotly.graph_objects as go

In [2]:
resultados = pd.read_csv('results.csv')

In [36]:
resultados

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
42348,2021-06-21,Finland,Belgium,0.0,2.0,UEFA Euro,Saint Petersburg,Russia,True
42349,2021-06-21,Netherlands,North Macedonia,3.0,0.0,UEFA Euro,Amsterdam,Netherlands,False
42350,2021-06-21,Ukraine,Austria,0.0,1.0,UEFA Euro,Bucharest,Romania,True
42351,2021-06-21,Uruguay,Chile,1.0,1.0,Copa América,Cuiaba,Brazil,True
42352,2021-06-21,Argentina,Paraguay,1.0,0.0,Copa América,Brasilia,Brazil,True

In [35]:
resultados = resultados[resultados['home_score']>=0]

In [37]:
chile = resultados[(resultados['home_team']=='Chile') | (resultados['away_team']=='Chile')]

In [38]:
chile

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
268,1910-05-27,Argentina,Chile,3.0,1.0,Friendly,Buenos Aires,Argentina,False
269,1910-05-29,Chile,Uruguay,0.0,3.0,Friendly,Buenos Aires,Argentina,True
270,1910-06-05,Argentina,Chile,5.0,1.0,Friendly,Buenos Aires,Argentina,False
273,1910-09-11,Chile,Argentina,0.0,3.0,Friendly,Viña del Mar,Chile,False
379,1913-09-21,Chile,Argentina,0.0,2.0,Friendly,Viña del Mar,Chile,False
...,...,...,...,...,...,...,...,...,...
42160,2021-06-03,Argentina,Chile,1.0,1.0,FIFA World Cup qualification,Santiago del Estero,Argentina,False
42256,2021-06-08,Chile,Bolivia,1.0,1.0,FIFA World Cup qualification,Santiago,Chile,False
42303,2021-06-14,Argentina,Chile,1.0,1.0,Copa América,Rio de Janeiro,Brazil,True
42338,2021-06-18,Chile,Bolivia,1.0,0.0,Copa América,Cuiaba,Brazil,True
42351,2021-06-21,Uruguay,Chile,1.0,1.0,Copa América,Cuiaba,Brazil,True

In [74]:
def marcador(df):
    if df.loc[:,'home_score'] > df.loc[:,'away_score']:
        df['r'] = 'Home'
    elif df.loc[:,'away_score'] > df.loc[:,'away_score']:
        df['r'] = 'Away'
    else:
        df['r'] = 'Tie'

In [49]:
chile.groupby('tournament')['date'].count()

tournament
Brazil Independence Cup           4
Confederations Cup                5
Copa América                    188
Copa Bernardo O'Higgins          10
Copa Carlos Dittborn             16
Copa Juan Pinto Durán            16
Copa del Pacífico                19
FIFA World Cup                   33
FIFA World Cup qualification    151
Friendly                        314
Kirin Cup                         2
Lunar New Year Cup                1
Millennium Cup                    4
Pan American Championship         9
Rous Cup                          2
Name: date, dtype: int64

In [53]:
chile['home_score'] = chile['home_score'].astype('int64')
chile['away_score'] = chile['away_score'].astype('int64')

C:\Users\Marco Ascuy\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Marco Ascuy\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [71]:
resultados['resultados'] = np.where(resultados.loc[:,'home_score'] > resultados.loc[:,'away_score'],'Local', 'Empate')
resultados['resultados'] = np.where(resultados.loc[:,'home_score'] < resultados.loc[:,'away_score'],'Visita', 'Empate')

C:\Users\Marco Ascuy\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Marco Ascuy\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [76]:
df =  chile.copy()

In [83]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,resultados
268,1910-05-27,Argentina,Chile,3,1,Friendly,Buenos Aires,Argentina,False,Chile
269,1910-05-29,Chile,Uruguay,0,3,Friendly,Buenos Aires,Argentina,True,Empate/Derrota
270,1910-06-05,Argentina,Chile,5,1,Friendly,Buenos Aires,Argentina,False,Chile
273,1910-09-11,Chile,Argentina,0,3,Friendly,Viña del Mar,Chile,False,Empate/Derrota
379,1913-09-21,Chile,Argentina,0,2,Friendly,Viña del Mar,Chile,False,Empate/Derrota
...,...,...,...,...,...,...,...,...,...,...
42160,2021-06-03,Argentina,Chile,1,1,FIFA World Cup qualification,Santiago del Estero,Argentina,False,Empate/Derrota
42256,2021-06-08,Chile,Bolivia,1,1,FIFA World Cup qualification,Santiago,Chile,False,Empate/Derrota
42303,2021-06-14,Argentina,Chile,1,1,Copa América,Rio de Janeiro,Brazil,True,Empate/Derrota
42338,2021-06-18,Chile,Bolivia,1,0,Copa América,Cuiaba,Brazil,True,Chile
42351,2021-06-21,Uruguay,Chile,1,1,Copa América,Cuiaba,Brazil,True,Empate/Derrota

In [84]:
df.loc[df['home_score'] > df['away_score'] , 'resultados'] = 'Local'
df.loc[df['home_score'] < df['away_score'] , 'resultados'] = 'Visita'
df.loc[df['home_score'] == df['away_score'] , 'resultados'] = 'Empate'

In [85]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,resultados
268,1910-05-27,Argentina,Chile,3,1,Friendly,Buenos Aires,Argentina,False,Local
269,1910-05-29,Chile,Uruguay,0,3,Friendly,Buenos Aires,Argentina,True,Visita
270,1910-06-05,Argentina,Chile,5,1,Friendly,Buenos Aires,Argentina,False,Local
273,1910-09-11,Chile,Argentina,0,3,Friendly,Viña del Mar,Chile,False,Visita
379,1913-09-21,Chile,Argentina,0,2,Friendly,Viña del Mar,Chile,False,Visita
...,...,...,...,...,...,...,...,...,...,...
42160,2021-06-03,Argentina,Chile,1,1,FIFA World Cup qualification,Santiago del Estero,Argentina,False,Empate
42256,2021-06-08,Chile,Bolivia,1,1,FIFA World Cup qualification,Santiago,Chile,False,Empate
42303,2021-06-14,Argentina,Chile,1,1,Copa América,Rio de Janeiro,Brazil,True,Empate
42338,2021-06-18,Chile,Bolivia,1,0,Copa América,Cuiaba,Brazil,True,Local
42351,2021-06-21,Uruguay,Chile,1,1,Copa América,Cuiaba,Brazil,True,Empate

In [88]:
df.loc[(df['home_team'] =='Chile') & (df['resultados'] =='Local') , 'R'] = 'Victoria'
df.loc[(df['home_team'] =='Chile') & (df['resultados'] =='Visita') , 'R'] = 'Derrota'
df.loc[(df['home_team'] =='Chile') & (df['resultados'] =='Empate') , 'R'] = 'Empate'

df.loc[(df['away_team'] =='Chile') & (df['resultados'] =='Local') , 'R'] = 'Derrota'
df.loc[(df['away_team'] =='Chile') & (df['resultados'] =='Visita') , 'R'] = 'Victoria'
df.loc[(df['away_team'] =='Chile') & (df['resultados'] =='Empate') , 'R'] = 'Empate'

In [89]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,resultados,R
268,1910-05-27,Argentina,Chile,3,1,Friendly,Buenos Aires,Argentina,False,Local,Derrota
269,1910-05-29,Chile,Uruguay,0,3,Friendly,Buenos Aires,Argentina,True,Visita,Derrota
270,1910-06-05,Argentina,Chile,5,1,Friendly,Buenos Aires,Argentina,False,Local,Derrota
273,1910-09-11,Chile,Argentina,0,3,Friendly,Viña del Mar,Chile,False,Visita,Derrota
379,1913-09-21,Chile,Argentina,0,2,Friendly,Viña del Mar,Chile,False,Visita,Derrota
...,...,...,...,...,...,...,...,...,...,...,...
42160,2021-06-03,Argentina,Chile,1,1,FIFA World Cup qualification,Santiago del Estero,Argentina,False,Empate,Empate
42256,2021-06-08,Chile,Bolivia,1,1,FIFA World Cup qualification,Santiago,Chile,False,Empate,Empate
42303,2021-06-14,Argentina,Chile,1,1,Copa América,Rio de Janeiro,Brazil,True,Empate,Empate
42338,2021-06-18,Chile,Bolivia,1,0,Copa América,Cuiaba,Brazil,True,Local,Victoria
42351,2021-06-21,Uruguay,Chile,1,1,Copa América,Cuiaba,Brazil,True,Empate,Empate

In [91]:
df.groupby(['tournament', 'R'])['date'].count()

tournament                    R
Brazil Independence Cup       Derrota       1
                              Victoria      3
Confederations Cup            Derrota       1
                              Empate        3
                              Victoria      1
Copa América                  Derrota      85
                              Empate       36
                              Victoria     67
Copa Bernardo O'Higgins       Derrota       6
                              Empate        2
                              Victoria      2
Copa Carlos Dittborn          Derrota       9
                              Empate        5
                              Victoria      2
Copa Juan Pinto Durán         Derrota       8
                              Empate        6
                              Victoria      2
Copa del Pacífico             Derrota       4
                              Empate        2
                              Victoria     13
FIFA World Cup                Derrota      15
                              Empate        7
                              Victoria     11
FIFA World Cup qualification  Derrota      58
                              Empate       32
                              Victoria     61
Friendly                      Derrota     119
                              Empate       69
                              Victoria    126
Kirin Cup                     Derrota       1
                              Empate        1
Lunar New Year Cup            Empate        1
Millennium Cup                Derrota       1
                              Victoria      3
Pan American Championship     Derrota       4
                              Empate        1
                              Victoria      4
Rous Cup                      Derrota       1
                              Empate        1
Name: date, dtype: int64